spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.50.1:3306/gulimall_wms?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-seckill
  redis:
    host: 192.168.50.1
    port: 6379
  rabbitmq:
    host: 192.168.50.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8700

logging:
  level:
    com.hyl.gulimall: debug
