spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.50.1:3306/gulimall_oms?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.50.1
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.50.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000
